### ISSUE TITLE
RSS feed broken

### ISSUE THREAD

**Issue by tallaxes** [itaysk/itaysk.github.io#4]
The RSS feed is currently [broken](https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fblog.itaysk.com%2Ffeed.xml) (XML Parsing Error: not well-formed)

**Comment by itaysk** [comment]
thanks for reporting! fixed in https://github.com/itaysk/itaysk.github.io/commit/b119781ee508f8166404e61449de01cffffb498b

(the issue was some control characters sneaked in to the text)
